import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FileUpload } from "primereact/fileupload";
import { Toolbar } from "primereact/toolbar";
import { DataTable } from "primereact/datatable";
import { Column } from "primereact/column";
import { useState, useEffect } from "react";
import { Button } from "primereact/button";
import { ConfirmPopup, confirmPopup } from "primereact/confirmpopup";

export default function Home() {
  const [files, setFiles] = useState<string[]>([]);

  useEffect(() => {
    (async () => {
      const res = await fetch("/api/files");
      const json = await res.json();
      setFiles(json);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Viblo K8S Volume Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfirmPopup />
      <main className={styles.main}>
        <Toolbar
          className="w-full"
          start={<h2>File Upload</h2>}
          end={
            <FileUpload
              mode="basic"
              name="file"
              url="/api/upload"
              accept="image/*"
              maxFileSize={1000000}
              auto
              chooseLabel="Browse"
              onUpload={(e) => {
                setFiles(JSON.parse(e.xhr.response));
              }}
            />
          }
        />
        <DataTable
          value={files.map((item) => ({ name: item }))}
          tableStyle={{ minWidth: "50rem" }}
          className="mt-5"
        >
          <Column field="name" header="Name"></Column>
          <Column
            field="actions"
            header="Actions"
            body={(rowData) => {
              return (
                <Button
                  icon="pi pi-times"
                  rounded
                  outlined
                  severity="danger"
                  aria-label="Cancel"
                  onClick={(e) => {
                    confirmPopup({
                      target: e.currentTarget,
                      message: "Are you sure you want to proceed?",
                      icon: "pi pi-exclamation-triangle",
                      accept: async () => {
                        await fetch("/api/files", {
                          method: "POST",
                          body: JSON.stringify({ file: rowData.name }),
                          headers: {
                            "Content-Type": "application/json",
                          },
                        });
                        setFiles(files.filter((item) => item !== rowData.name));
                      },
                    });
                  }}
                />
              );
            }}
          ></Column>
        </DataTable>
      </main>
    </>
  );
}
